[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
squad_mint_multi_sig = "BW1dtKfuqUPZxyYKfFCgUwo8tzqnGfw9of5L4yfAzuRz"

[programs.devnet]
squad_mint_multi_sig = "BW1dtKfuqUPZxyYKfFCgUwo8tzqnGfw9of5L4yfAzuRz"

[registry]
url = "https://api.apr.dev"

#[provider]
#cluster = "devnet"
#wallet = "~/keypair-dev-1.json"

[provider]
cluster = "localnet"
wallet = "~/keypair-dev-1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
